version: '3.8'

services:
  backend-prod:
    image: ${ACR_LOGIN_SERVER}/note-app-backend:latest
    container_name: note-app-backend-prod
    env_file:
      - ./be/.env.production
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
    - backend_data:/app/data

  frontend-prod:
    image: ${ACR_LOGIN_SERVER}/note-app-frontend:latest
    container_name: note-app-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - ./fe/.env.production
    depends_on:
      - backend-prod

volumes:
  backend_data: