version: '3.8'

services:
  backend-prod:
    image: ${ACR_LOGIN_SERVER}/note-app-backend:latest
    container_name: note-app-backend-prod
    environment:
      - DATABASE_URL="${DATABASE_URL}"
      - ACCESS_TOKEN_SECRET="${ACCESS_TOKEN_SECRET}"
      - REFRESH_TOKEN_SECRET="${REFRESH_TOKEN_SECRET}"
    restart: unless-stopped
    ports:
      - "8080:8080"

  frontend-prod:
    image: ${ACR_LOGIN_SERVER}/note-app-frontend:latest
    container_name: note-app-frontend-prod
    restart: unless-stopped
    environment:
     - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    env_file:
      - ./fe/.env.production
    depends_on:
      - backend-prod