version: '3.8'

services:
  backend-prod:
    image: ${ACR_LOGIN_SERVER}/note-app-backend:latest
    container_name: note-app-backend-prod
    env_file:
      - ./be/.env.production
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
    - backend_data:/app/data
    networks:
      - app-network

  frontend-prod:
    image: ${ACR_LOGIN_SERVER}/note-app-frontend:latest
    container_name: note-app-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./fe/.env.production
    depends_on:
      - backend-prod
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge