name: Build Docker Images

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment to build for production'

env:
  BE_IMAGE_NAME: note-app-backend
  FE_IMAGE_NAME: note-app-frontend
  BE_DOCKERFILE: ./be/Dockerfile.prod
  FE_DOCKERFILE: ./fe/Dockerfile.prod

jobs:
  build:
    name: Build and Push Images
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for better caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          driver: docker-container

      # Prevent rate limiting for base images
      - name: Docker Hub Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Login to Azure Container Registry
      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      # Build and push backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./be
          file: ${{ env.BE_DOCKERFILE }}
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.BE_IMAGE_NAME }}:latest,${{ secrets.ACR_LOGIN_SERVER }}/${{ env.BE_IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          cache-from: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.BE_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.BE_IMAGE_NAME }}:buildcache,mode=max

      # Build and push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./fe
          file: ${{ env.FE_DOCKERFILE }}
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.FE_IMAGE_NAME }}:latest,${{ secrets.ACR_LOGIN_SERVER }}/${{ env.FE_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.FE_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.FE_IMAGE_NAME }}:buildcache,mode=max
          
      # Store image info for later jobs
      - name: Save image information
        id: image-info
        run: |
          echo "BE_IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.BE_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "FE_IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.FE_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT