name: Deploy Application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment to deploy to production'

jobs:
  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: '{"clientId":"${{ secrets.AZURE_APPLICATION_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      # Handle database access through firewall
      - name: Database Access Setup
        uses: ./.github/actions/db-firewall
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          server-name: ${{ secrets.AZURE_POSTGRES_SERVER_NAME }}
      
      # Create deployment configuration file
      - name: Create deployment config
        run: |
          cat <<EOF > deployment.env 
          ACR_LOGIN_SERVER="${{ secrets.ACR_LOGIN_SERVER }}"
          ACCESS_TOKEN_SECRET="${{ secrets.ACCESS_TOKEN_SECRET }}"
          REFRESH_TOKEN_SECRET="${{ secrets.REFRESH_TOKEN_SECRET }}"
          DATABASE_URL="${{ secrets.DATABASE_URL }}"
          BE_IMAGE="${{ secrets.ACR_LOGIN_SERVER }}/note-app-backend:${{ github.sha }}"
          FE_IMAGE="${{ secrets.ACR_LOGIN_SERVER }}/note-app-frontend:${{ github.sha }}"
          DEPLOY_TIMESTAMP=$(date +%s)
          EOF
      
      # Deploy to Azure VM
      - name: Deploy to Azure
        uses: ./.github/actions/vm-deploy
        with:
          vm-ip: ${{ secrets.AZURE_VM_IP }}
          vm-user: ${{ secrets.AZURE_VM_USER }}
          ssh-key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          app-path: note-app
          azure-client-id: ${{ secrets.AZURE_APPLICATION_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          acr-login-server: ${{ secrets.ACR_LOGIN_SERVER }}